### ISSUE TITLE
Relayer vulnerability discussion

### ISSUE THREAD

**Issue by 0xYao** [smrpn/EBonAB#4]
https://github.com/smrpn/Account2/blob/1d742ce8d784580518bd82a3cf994eeb1a802b6e/src/Account2.sol#L15

This is mainly a discussion rather than an issue. If the relayer is compromised, that means the attacker can modify the target address and the calldata which is a vulnerability, right?

**Comment by 0xethsign** [comment]
do you mean like a reentrancy attack? this is a possibility i think.

**Comment by 0xYao** [comment]
No, I was thinking of something else but I realised the signature verification operation should guard against it.
